name: Format suggestions

on:
  pull_request:
    # this argument is not required if you don't use the `suggestion-label` input
    types: [ opened, reopened, synchronize, labeled, unlabeled ]

# Grant the workflow permission to comment on PRs (needed by reviewdog in julia-format action)
permissions:
  contents: read
  pull-requests: write

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/julia-format@v4
        with:
          version: '2' # Set `version` to '1.0.54' if you need to use JuliaFormatter.jl v1.0.54 (default: '1')
          suggestion-label: '' # leave this unset or empty to show suggestions for all PRs